In [6]:
import numpy as np

In [7]:
#Q1. Create a 3×3 array filled with random numbers and print its shape.

In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6] , [7, 8, 9]])
print(arr.shape)

(3, 3)


In [10]:
#Q2. Convert an array of floats [1.1, 2.2, 3.3] into integers.

In [13]:
arr1 = np.array([1.1, 2.2, 3.3] , dtype=np.int32)
print(arr1)

[1 2 3]


In [14]:
#Q3. Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].

In [16]:
arr2 = np.array([1, 2, 3, 4, 5, 6])
idx = [ 1 , 3 , 5 ]
print(arr2[idx])

[2 4 6]


In [17]:
#Q4. Reshape a 1D array of size 9 into a 3×3 matrix.

In [20]:
arr3 = np.array([1,2,3,4,5,6,7,8,9])
reshape = arr3.reshape(3,3)
print(reshape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
#Q5. Use boolean masking to filter numbers greater than 50 in an array.

In [23]:
arr4 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
arr4[arr4>50]

array([ 60,  70,  80,  90, 100])