In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
result = arr ** 2  # Vectorized operation
print(result)  # Output: [1 4 9 16 25]
arr.sum(axis=0)

[ 1  4  9 16 25]


np.int64(15)

In [2]:
# Broadcasting is a powerful feature of NumPy that allows you to perform operations on arrays of different shapes without creating copies. It “stretches” smaller arrays across larger arrays in a memory-efficient way, avoiding the overhead of creating multiple copies of data.
arr1 = np.array([1, 2, 3])
arr2 = np.array([10, 20, 30])

result = arr1 + arr2  # Element-wise addition
print(result)  

[11 22 33]


In [3]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3])

result = arr1 + arr2  # Broadcasting arr2 across arr1
print(result)

[[2 4 6]
 [5 7 9]]


In [4]:
# Simulating a dataset (5 samples, 3 features)
data = np.array([[10, 20, 30],
                 [15, 25, 35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])

# Calculating mean and standard deviation for each feature (column)
mean = data.mean(axis=0)
std = data.std(axis=0)
print(mean)

# Normalizing the data using broadcasting
normalized_data = (data - mean) / std

print(normalized_data)

[20. 30. 40.]
[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]


In [5]:
#Loops are slow because Python's interpreter adds overhead, making iteration less efficient.
#Vectorization allows to apply operations to entire arrays at once, greatly improving performance by utilizing NumPy’s optimized C backend.
#Broadcasting enables operations between arrays of different shapes by automatically stretching the smaller array to match the shape of the larger array, without creating additional copies.
#Real-world use: Broadcasting can be used in data science tasks, such as normalizing datasets, without sacrificing memory or performance.