In [1]:
import numpy as np

In [2]:
!pip install numpy

In [3]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])  # 1D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array basically kind of list of list

print(arr1)  # [1 2 3 4 5]
print(arr2)  
# [[1 2 3]
#  [4 5 6]]

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [5]:
np.zeros((3,4)) #kind of like 3x4 zero matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [7]:
np.full((3,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [9]:
np.eye(7) #identity matrix

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [11]:
np.arange(1, 10, 2) # [1, 3, 5, 7, 9] (10 is the outmost range here with every +2)

array([1, 3, 5, 7, 9])

In [12]:
np.linspace(0, 1, 5) # [0. 0.25 0.5 0.75 1.] (evenly spaced)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
arr = np.array([[10, 20, 30], [40, 50, 60]])

print("Shape:", arr.shape)   # (2, 3) → 2 rows, 3 columns
print("Size:", arr.size)     # 6 → total elements
print("Dimensions:", arr.ndim) # 2 → 2D array
print("Data type:", arr.dtype) # int64 (or int32 on Windows)

Shape: (2, 3)
Size: 6
Dimensions: 2
Data type: int64


In [17]:
#converting data types
arr = np.array([1, 2, 3], dtype=np.float32)  # Explicit type
print(arr)
print(arr.dtype)  # float32

arr_int = arr.astype(np.int32)  # Convert float to int
print(arr_int)  # [1 2 3]
print(arr_int.dtype)

[1. 2. 3.]
float32
[1 2 3]
int32


In [22]:
#Reshaping and Flattening Arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)  # (2, 3)
 
reshaped = arr.reshape((3, 2))  # Change shape
print(reshaped)

arr.flatten() # Convert 2D → 1D

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


array([1, 2, 3, 4, 5, 6])