In [1]:
import numpy as np

In [2]:
arr = np.array([10, 20, 30, 40])
print(arr[0])  # 10
print(arr[-1]) # 40

10
40


In [3]:
arr

array([10, 20, 30, 40])

In [4]:
b = arr[2:4]

In [5]:
b

array([30, 40])

In [6]:
b[0] = 333333333

In [7]:
b

array([333333333,        40])

In [8]:
arr

array([       10,        20, 333333333,        40])

Slicing returns a view, not a copy! Changes affect the original array

In [10]:
arr1 = np.array([1 , 66 ,74,32, 646, 34, 62])

In [12]:
arr1[[1,4,6]]  #1,4,6 are indices

array([ 66, 646,  62])

In [16]:
arr1[arr1>35]  #>35 every element showing

array([ 66,  74, 646,  62])