In [1]:
import numpy as np

arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
print(np.sum(arr, axis=0))  # Sum along rows (down each column)
print(np.sum(arr, axis=1))  # Sum along columns (across each row)

[12 15 18]
[ 6 15 24]


In [3]:
arr[0][1] #0th row , 1st column
arr[0 , 1]

np.int64(2)

In [4]:
# Accessing an element
print(arr[1, 2])  # Row index 1, Column index 2 → Output: 6

6


In [5]:
print(arr[0:2, 1:3])  # Extracts first 2 rows(0:2) and last 2 columns(1:3)

[[2 3]
 [5 6]]


In [6]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])

# Output of arr3D.shape is → (depth, rows, columns)
print(arr3D.shape)  # Output: (2, 2, 3) 

(2, 2, 3)


In [7]:
# First sheet( here it means [1, 2, 3], [4, 5, 6]), 1 is the second row,2 is the third column
print(arr3D[0, 1, 2])  # Output: 6

print(arr3D[:, 0, :])   # Get the first row from both sheets ( : mean all sheets , o means 1st row , : mean all columns)

6
[[1 2 3]
 [7 8 9]]


In [8]:
# Changing Data Along an Axis
arr3D[:, 0, :] = 0
print(arr3D)

[[[ 0  0  0]
  [ 4  5  6]]

 [[ 0  0  0]
  [10 11 12]]]


In [9]:
#Summary
#Axis 0 = rows (vertical movement), Axis 1 = columns (horizontal movement)
#Indexing works as arr[row, column] for 2D arrays and arr[depth, row, column] for 3D arrays
#Slicing allows extracting subarrays